name: shotani_app
description: A new Flutter project.

version: 1.0.0+1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  cached_network_image: ^2.5.1
  cloud_firestore: ^0.16.0+1
  cupertino_icons: ^1.0.2
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.15
  firebase_remote_config: ^0.6.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  flutter_local_notifications: ^4.0.1+2
  freezed_annotation: ^0.14.2
  grouped_list: ^4.1.0
  hooks_riverpod: ^0.14.0+4
  intl: ^0.16.1
  json_serializable: ^5.0.0
  launch_review: ^3.0.1
  logger: ^1.0.0
  package_info: ^2.0.2
  pub_semver: ^2.0.0
  quiver: ^2.1.5
  ribbon: ^0.0.1
  shared_preferences: ^2.0.6
  table_sticky_headers: ^2.0.0
  url_launcher: ^6.0.5
  webview_flutter: ^2.0.12

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

dependency_overrides:
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0
  json_serializable: ^3.5.1
  # flutter pub run build_runner build --delete-conflicting-outputs

flutter_icons:
  android: true
  ios: true
  adaptive_icon_foreground: "assets/icon/adaptive_back.png"
  adaptive_icon_background: "assets/icon/adaptive_back.png"
  image_path: "assets/icon/icon.png"
  #flutter pub pub run flutter_launcher_icons:main

flutter_native_splash:
  # color: "#f3584e"
  background_image: "assets/splash/background.png"
  # flutter pub run flutter_native_splash:create

flutter:
  uses-material-design: true
